Implemented fit method for the normal model based on the fit method for lognormal one. Added initial guess of numerical optimization to method's arguments in both models.
ynouri/pySABR pull request #7
Opened 2022-01-23 17:00 UTC by v-tsepelev

I was using your PySABR package in my own derivatives project and found out there is a lack of calibration implemented for the Normal (Bachelier) model, however it's very easy to add it based on already existing fit method in the lognormal class. I also found it helpful to have an initial guess for calibrating model parameters to be explicitly available.

2022-03-01 04:36 UTC, ynouri commented on pysabr/models/hagan_2002_normal_sabr.py
> +        return [alpha, self.rho, self.volvol]
This is great, thank you @v-tsepelev . Would it be possible to add a unit test covering this new fit method? Something similar to https://github.com/ynouri/pysabr/blob/master/pysabr/tests/hagan_2002_lognormal_sabr/test_fit.py

2022-03-01 04:36 UTC, ynouri requested changes
Thanks for this contribution! With a unit test this should be good to go.
PS: I changed the PR base to `ynouri:master`. I think this is what you had in mind right

2022-04-12 14:36 UTC, v-tsepelev commented
Please take a look at a unit test for normal fit method. Sorry it took me some time to get back to it.

2022-04-21 19:39 UTC, ynouri approved these changes

2022-04-21 19:39 UTC, merged